# -*- coding: utf-8 -*-
"""WS_MYRIAM_AIT_SAID.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVp6Z3eqZk7gNX48_mYzD3DDC06M9cdV

# **Part 1: Web scrapping and knowledge base construction**

'''
In this lab, we are building a pipeline to extract structured knowledge
from text and represent it as a knowledge graph.

Steps we have followed:
- Text Preprocessing : Cleaning and normalizing text.
- Named Entity Recognition (NER) : Identifying entities in text.
- Relation Extraction (RE) : Finding relations between entities.
- Knowledge Graph Construction : Storing the extracted knowledge as RDF triples.
- SPARQL Queries : Interacting with our knowledge graph.
- Web Scraping : Enriching our graph with real-world news data.
- Graph embedding and enrichment
- Training and evaluating models on the constructed graph
- Visualizing the results
'''

**Task 1: Model for NER**
"""

import os
import re
import json
import time
import torch
import string
import random
import logging
import zipfile
import requests
import urllib.request
import urllib.parse
import socket

import numpy as np
import pandas as pd
import bs4
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import spacy
import spacy.cli
import datasets
from datasets import load_dataset

import sklearn_crfsuite
from sklearn_crfsuite import CRF, metrics
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score
from sklearn.manifold import TSNE

from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, DC, OWL, FOAF, RDFS

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import TimeoutException, NoSuchElementException, WebDriverException, ElementClickInterceptedException
from selenium.common.exceptions import *

from pykeen.triples import TriplesFactory
from pykeen.pipeline import pipeline
from pykeen.evaluation.rank_based_evaluator import RankBasedEvaluator
from plotly.subplots import make_subplots
import plotly.graph_objects as go

from unidecode import unidecode
from SPARQLWrapper import SPARQLWrapper, JSON
from collections import defaultdict

# Autoriser le code distant en ajoutant trust_remote_code=True
dataset = load_dataset("conll2003", trust_remote_code=True)

# Accéder aux sous-ensembles
train_dataset = dataset['train']
validation_dataset = dataset['validation']
test_dataset = dataset['test']

# Affichage du mapping des labels NER
ner_labels = dataset["train"].features["ner_tags"].feature
print(f"Mapping of NER labels: {ner_labels}")

# Exemple sur la première instance du dataset
tokens = train_dataset[0]["tokens"]
ner_tags = train_dataset[0]["ner_tags"]
ner_labels_text = [ner_labels.int2str(tag) for tag in ner_tags]

print("Tokens with their NER labels:")
for token, label in zip(tokens, ner_labels_text):
    print(f"{token}: {label}")

# Mapping des POS tags
pos_labels = dataset["train"].features["pos_tags"].feature
pos_tags = train_dataset[0]["pos_tags"]
pos_labels_text = [pos_labels.int2str(tag) for tag in pos_tags]

print("Mapping of the POS tags for the first example:")
for token, pos in zip(tokens, pos_labels_text):
    print(f"{token}: {pos}")

# Mapping des chunk tags
chunk_labels = dataset["train"].features["chunk_tags"].feature
chunk_tags = train_dataset[0]["chunk_tags"]
chunk_labels_text = [chunk_labels.int2str(tag) for tag in chunk_tags]

print("Mapping of the chunk tags for the first example:")
for token, chunk in zip(tokens, chunk_labels_text):
    print(f"{token}: {chunk}")

"""Ok, now that we understand how the tokens are labeled, we can start text cleaning and preprocessing"""

# We download the required NLTK data for the text cleaning
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

#The en_ner_conll03 model wasn’t available for spaCy v3.8, so I used the best alternative.
#I used spaCy's en_core_web_trf model instead of en_ner_conll03 because it’s the most powerful transformer-based English NER model available in spaCy,
#and it offers state-of-the-art performance for comparison with my CRF model.

nlp = spacy.load("en_core_web_trf")

def preprocess_text(text):
    # we use this function To convert to lowercase
    text = text.lower()

    # To tokenize our text
    tokens = word_tokenize(text)

    # We remove the punctuation (except hyphens because it gives other words)
    tokens = [word for word in tokens if word not in string.punctuation or word == "-"]

    # We remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]

    # We apply the lemmatization
    tokens = [token.lemma_ for token in nlp(" ".join(tokens))]

    return tokens

# Example sentence to see if it works as expected
text = "The US accepts a FrEnch chat to welcome english lamb."
cleaned_text = preprocess_text(text)
print("Cleaned Tokens:", cleaned_text)

"""We convert the list of words into a single string to ensure proper NLP processing, especially for lemmatization and stopword removal (NLP tools work better when processing an entire sentence).
Once the processing is done, we can split it back into tokens.
"""

# Now we can preprocess the whole dataset with the function that we defined above
texts = [" ".join(sentence["tokens"]) for sentence in dataset["train"]]
stop_words = set(stopwords.words("english"))
# On utilise nlp.pipe pour le traitement par batch car trop lent sinon
docs = list(nlp.pipe(texts, batch_size=16))
preprocessed_sentences = [
    [token.lemma_ for token in doc if token.text.lower() not in stop_words and (token.is_alpha or token.text == "-")]
    for doc in docs
]
# exemple
print(preprocessed_sentences[:3])

"""**Named Entity Recognition (NER):**

Before training the CRF model, we need to convert words into feature representations.
"""

# Extracting useful features for NER
# The CRF model needs features to learn patterns in text.
def word_features(sentence, index):
    word = sentence["tokens"][index]

    features = {
        "word.lower()": word.lower(),  # Lowercased word
        "word.isupper()": word.isupper(),  # Checks if the word is fully uppercase
        "word.istitle()": word.istitle(),  # Checks if the word starts with an uppercase letter
        "word.isdigit()": word.isdigit(),  # Checks if the word is a number
    }

    # Contextual Features: Adding information about surrounding words
    if index > 0:
        features["prev_word.lower()"] = sentence["tokens"][index - 1].lower()
    else:
        features["BOS"] = True  # Beginning of sentence marker

    if index < len(sentence["tokens"]) - 1:
        features["next_word.lower()"] = sentence["tokens"][index + 1].lower()
    else:
        features["EOS"] = True  # End of sentence marker

    return features

# We convert the dataset into feature format
def extract_features(dataset):
    return [[word_features(sentence, i) for i in range(len(sentence["tokens"]))] for sentence in dataset]

# here we get the mapping of integer NER labels to text labels
ner_label_map = dataset["train"].features["ner_tags"].feature

# we convert integer labels to text labels
def convert_labels_to_text(dataset):
    return [[ner_label_map.int2str(tag) for tag in sentence["ner_tags"]] for sentence in dataset]

#conversion for both training and test sets
y_train = convert_labels_to_text(dataset["train"])
y_test = convert_labels_to_text(dataset["test"])

# we extract features for CRF
X_train = extract_features(dataset["train"])
X_test = extract_features(dataset["test"])

# Training the CRF model for Named Entity Recognition
# The model will learn to classify words based on the extracted features
crf = CRF(
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=False
)
crf.fit(X_train, y_train)

# We predict on test data
y_pred = crf.predict(X_test)

# [1]we print the classification report to evaluate our model
print(metrics.flat_classification_report(y_test, y_pred))

# we extract and save named entities with positions
def extract_named_entities_with_positions(sentence):
    doc = nlp(" ".join(sentence["tokens"]))
    entities = [(ent.text, ent.label_, ent.start, ent.end) for ent in doc.ents]
    return entities

named_entities_positions = [extract_named_entities_with_positions(sentence) for sentence in dataset["train"]]

# Saving extracted entities
total_entities = []
for entities in named_entities_positions:
    for entity in entities:
        total_entities.append(entity)

nlp = spacy.load("en_core_web_trf")  # Meilleur modèle dispo pour NER
texts = [" ".join(sentence["tokens"]) for sentence in dataset["train"]]
docs = list(nlp.pipe(texts, batch_size=16))
named_entities_positions = [
    [(ent.text, ent.label_, ent.start, ent.end) for ent in doc.ents]
    for doc in docs
]

#On Aplatit la liste pour regrouper toutes les entités extraites et on test
total_entities = [ent for ents in named_entities_positions for ent in ents]
print("\nExtracted Named Entities with their positions (first 5):")
print(total_entities[:5])

"""**1. Comparaison CRF vs spaCy avec scores numériques**"""

def evaluate_spacy(nlp, dataset):
    y_true, y_pred = [], []

    ner_label_map = dataset.features["ner_tags"].feature
    valid_labels = set(ner_label_map.names)
    texts = [" ".join(sentence["tokens"]) for sentence in dataset]
    true_tags_list = [[ner_label_map.int2str(tag) for tag in sentence["ner_tags"]] for sentence in dataset]
    tokens_list = [sentence["tokens"] for sentence in dataset]
    docs = list(nlp.pipe(texts, batch_size=16))
    for tokens, true_tags, doc in zip(tokens_list, true_tags_list, docs):
        pred_tags = ["O"] * len(tokens)

        for ent in doc.ents:
            ent_tokens = ent.text.split()
            for i, token in enumerate(tokens):
                if token in ent_tokens:
                    tag = f"B-{ent.label_}" if i == 0 else f"I-{ent.label_}"
                    if tag in valid_labels:
                        pred_tags[i] = tag

        y_true.append(true_tags)
        y_pred.append(pred_tags)

    return y_true, y_pred

def compute_scores(y_true, y_pred, zero_division=0):
    y_true_flat = [tag for sent in y_true for tag in sent]
    y_pred_flat = [tag for sent in y_pred for tag in sent]

    # Labels présents dans le dataset (sauf 'O' si tu veux l'exclure)
    all_labels = sorted(list(set(y_true_flat)))

    precision = precision_score(y_true_flat, y_pred_flat, average='weighted', labels=all_labels, zero_division=zero_division)
    recall = recall_score(y_true_flat, y_pred_flat, average='weighted', labels=all_labels, zero_division=zero_division)
    f1 = f1_score(y_true_flat, y_pred_flat, average='weighted', labels=all_labels, zero_division=zero_division)

    return precision, recall, f1

# CRF report
print("[CRF - Classification Report]")
print(metrics.flat_classification_report(y_test, y_pred))

# spaCy report
y_true_spacy, y_pred_spacy = evaluate_spacy(nlp, dataset["test"])
print("\n[SpaCy - Classification Report]")
print(metrics.flat_classification_report(y_true_spacy, y_pred_spacy, zero_division=0))

# [2] Évaluation CRF (valeurs numériques pour la comparaison avec spaCy)
crf_precision, crf_recall, crf_f1 = compute_scores(y_test, y_pred)
spacy_precision, spacy_recall, spacy_f1 = compute_scores(y_true_spacy, y_pred_spacy, zero_division=0)

print("\n[Scores Comparison]")
scores_df = pd.DataFrame({
    "Model": ["CRF", "spaCy"],
    "Precision": [crf_precision, spacy_precision],
    "Recall": [crf_recall, spacy_recall],
    "F1-score": [crf_f1, spacy_f1]
})

scores_df.style.format({
    "Precision": "{:.3f}",
    "Recall": "{:.3f}",
    "F1-score": "{:.3f}"
})

# Récupérer les entités CRF (depuis y_pred)
entities_crf = set()
for sentence, tags in zip(dataset["test"], y_pred):
    for token, tag in zip(sentence["tokens"], tags):
        if tag != "O":
            entities_crf.add(token)

# Récupérer les entités spaCy (depuis total_entities déjà extrait)
entities_spacy = set(ent[0] for ent in total_entities)  # ent[0] = ent.text

# Affichage
print(f"\nNombre d'entités uniques reconnues par CRF : {len(entities_crf)}")
print(f"Nombre d'entités uniques reconnues par spaCy : {len(entities_spacy)}")

# Optionnel : aperçu
print("\nAperçu des entités CRF :", list(entities_crf)[:10])
print("Aperçu des entités spaCy :", list(entities_spacy)[:10])

"""**Relation Extraction (RE)**"""

# Charger le modèle spaCy
nlp = spacy.load("en_core_web_sm")

# Initialiser le graphe RDF
g = Graph()
EX = Namespace("http://example.org/")

def clean_uri(entity):
    entity = unidecode(entity.lower().strip())
    entity = re.sub(r'[^\w]+', '_', entity)   # remplace tout groupe non alphanumérique par un _
    return entity.strip('_')

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^\w\s\-]', '', text)
    text = text.lower()
    tokens = word_tokenize(text)
    return " ".join([t for t in tokens if t not in stopwords.words('english')])

# Named Entity Recognition
def extract_entities(text):
    doc = nlp(text)
    return [(ent.text, ent.label_) for ent in doc.ents]

# Relation Extraction: subject-verb-object triplets
def extract_relations(text):
    doc = nlp(text)
    triples = []

    for sent in doc.sents:
        for token in sent:
            # X is a Y
            if token.dep_ == "nsubj" and token.head.lemma_ == "be":
                subject = token.text
                for child in token.head.children:
                    if child.dep_ == "attr" or child.dep_ == "acomp":
                        obj = child.text
                        triples.append((subject, "is_a", obj))

            # X named Y
            if token.dep_ == "nsubjpass" and token.head.lemma_ == "name":
                subject = token.text
                for child in token.head.children:
                    if child.dep_ == "agent":
                        for obj in child.children:
                            if obj.dep_ == "pobj":
                                triples.append((obj.text, "named", subject))

            # X's Y (possessive)
            if token.dep_ == "poss":
                possessor = token.text
                for child in token.head.children:
                    if child.dep_ == "attr":
                        triples.append((possessor, token.head.lemma_, child.text))

    return triples
# Texte de test
text = "Myriam was born in Canada."

# Extraction
entities = extract_entities(text)
relations = extract_relations(text)

# Intégration des entités dans le graphe RDF
for ent, label in entities:
    g.add((URIRef(EX + clean_uri(ent)), URIRef(EX + "hasType"), URIRef(EX + label)))

# Intégration des relations dans le graphe RDF
for subj, pred, obj in relations:
    g.add((URIRef(EX + clean_uri(subj)), URIRef(EX + clean_uri(pred)), URIRef(EX + clean_uri(obj))))

# Affichage des triplets RDF (lisibles)
print("\nTriplets RDF extraits :")
for s, p, o in g:
    print(f"{s} --{p}--> {o}")

# Exemple de requête SPARQL qui fonctionne
print("\n[SPARQL] Entities and their types :")
query = """
SELECT ?entity ?type WHERE {
  ?entity <http://example.org/hasType> ?type .
}
"""
for row in g.query(query):
    print(f"Entity: {row.entity}, Type: {row.type}")

"""**Knowledge Graph Construction**"""

#test
triples = [
    ("Apple", "founded_by", "Steve Jobs"),
    ("Steve Jobs", "lived_in", "California")
]

for subj, pred, obj in triples:
    g.add((URIRef(EX + clean_uri(subj)), URIRef(EX + clean_uri(pred)), URIRef(EX + clean_uri(obj))))

# Now we serializing and print our graph
print(g.serialize(format="turtle"))

"""**SparQl Queries**"""

# Querying the knowledge graph to retrieve extracted RDF triplets
# This will return a list of (subject, predicate, object) relations
print("\n[SPARQL] Relations between entities (triplets) :")
query = """
SELECT ?subject ?predicate ?object WHERE {
  ?subject ?predicate ?object .
}
LIMIT 10
"""
# Displaying extracted knowledge in a structured format for g knowledge graph example
for row in g.query(query):
    print(f"{row.subject} --{row.predicate}--> {row.object}")

text = "Myriam was born in Canada."
# Add entities with type
entities = extract_entities(text)
for ent, label in entities:
    g.add((URIRef(EX + clean_uri(ent)), URIRef(EX + "hasType"), URIRef(EX + label)))

# Check if hasType triplets are present
print("\nTriplets hasType présents dans le graphe :")
for s, p, o in g:
    if "hasType" in str(p):
        print(f"{s} --hasType--> {o}")

# Querying the knowledge graph to list all entities classified as "PERSON"
print("\n[SPARQL] entities that have the type PERSON :")
query = """
SELECT ?entity WHERE {
  ?entity <http://example.org/hasType> <http://example.org/PERSON> .
}
"""
# Displaying recognized PERSON entities
for row in g.query(query):
    print(row.entity)

# Displaying recognized predicate actions by Myriam
print("\n[SPARQL] Realized actions by Myriam :")
query = """
SELECT ?predicate ?object WHERE {
  <http://example.org/Myriam> ?predicate ?object .
}
"""
for row in g.query(query):
    print(f"Myriam --{row.predicate}--> {row.object}")

"""**Web Scraping**"""

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.google.com")

# Télécharger le fichier d'installation Chrome pour Windows
url = "https://dl.google.com/chrome/install/latest/chrome_installer.exe"
file_path = "chrome_installer.exe"
urllib.request.urlretrieve(url, file_path)

# Lancer l'installation (optionnel, nécessite autorisation)
os.system(file_path)

"""**Task 2: Pipeline for Knowledge Graph Construction**"""

# Web scraping articles from NPR
def fetch_npr_articles():
    url = "https://www.npr.org/sections/world/"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html.parser")
    articles = []

    for link in soup.select('article h2 a')[:10]:
        try:
            title = link.get_text(strip=True)
            article_url = link['href']
            article_response = requests.get(article_url)
            article_soup = BeautifulSoup(article_response.content, 'html.parser')

            # Try multiple ways to extract article text
            paragraphs = article_soup.select('article p')
            if not paragraphs:
                paragraphs = article_soup.select('div[class*="article"] p')
            if not paragraphs:
                paragraphs = article_soup.find_all('p')  # fallback

            content = " ".join([p.get_text(strip=True) for p in paragraphs])
            articles.append({'title': title, 'url': article_url, 'content': content})
        except Exception as e:
            print("Article error:", e)
            continue
    return articles

# Run the complete pipeline
def pipeline():
    articles = fetch_npr_articles()
    print(f"{len(articles)} articles retrieved.\n")

    graph = Graph()
    for article in articles:
        print(f"--- {article['title']} ---")
        print(f"URL: {article['url']}\n")

        raw_text = article['content']
        if not raw_text.strip():
            print("⚠ Empty or failed article.")
            continue

        ents = extract_entities(raw_text)
        rels = extract_relations(raw_text)
        build_kg(rels, graph)

        if ents:
            print("Entities:")
            for ent in ents:
                print(f" - {ent[0]} ({ent[1]})")
        else:
            print("No entities found.")

        if rels:
            print("Triples:")
            for triple in rels:
                print(f" - {triple}")
        else:
            print("No triples extracted.")
        print()

    print("=== RDF Graph ===")
    print(graph.serialize(format="turtle"))

    return graph
# Launch the pipeline
g=pipeline()

print(f"Total number of RDF triples: {len(g)}")
entities = set()
for s, p, o in g:
    entities.add(s)
    entities.add(o)

print(f"Total number of unique entities: {len(entities)}")

"""**Enrichment**"""

# Function to enrich from DBpedia
def enrich_with_dbpedia(entity_name):
    sparql = SPARQLWrapper("http://dbpedia.org/sparql")
    print(entity_name)
    query = f"""
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    SELECT DISTINCT ?related ?relation WHERE {{
        ?s rdfs:label "{entity_name.title()}"@en .
        ?s ?relation ?related .
        ?related rdfs:label ?label .
        FILTER(LANG(?label) = 'en')
    }} LIMIT 100
    """
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    try:
        results = sparql.query().convert()
        print(results)
        return [(entity_name, r['relation']['value'], r['related']['value']) for r in results['results']['bindings']]
    except:
        return []

# === 1. Conversion of the original RDF graph + DBpedia enrichment ===
print(" Generating enriched triples...")
triples = [[str(s), str(p), str(o)] for s, p, o in g]

# Extract entities from the original graph
entities = set()
for s, p, o in g:
    entities.add(str(s).split("/")[-1].replace("_", " "))
    entities.add(str(o).split("/")[-1].replace("_", " "))

# Enrichment with DBpedia
for ent in list(entities)[:100]:  # Limit to avoid overload
    enriched = enrich_with_dbpedia(ent)
    for s, p, o in enriched:
        triples.append([f"http://example.org/{s.replace(' ', '_')}", p, o])

triples_array = np.array(triples)
print(f" Total triples after enrichment: {len(triples_array)}")

from rdflib import URIRef

print("Generating enriched triples...")
entities = set()
for s, p, o in g:
    entities.add(str(s).split("/")[-1].replace("_", " "))
    entities.add(str(o).split("/")[-1].replace("_", " "))

# Enrich and add new triples directly into the graph
for ent in list(entities)[:100]:  # limit for performance
    enriched = enrich_with_dbpedia(ent)
    for subj, pred, obj in enriched:
        subj_uri = URIRef(f"http://example.org/{subj.replace(' ', '_')}")
        pred_uri = URIRef(pred)
        obj_uri = URIRef(obj)
        g.add((subj_uri, pred_uri, obj_uri))

print(f"\nTotal number of RDF triples after enrichment: {len(g)}")

entities = set()
for s, p, o in g:
    entities.add(s)
    entities.add(o)

print(f"Total number of unique entities after enrichment: {len(entities)}")

"""**Part 2: Knowledge Graph Embedding**

**Training and evaluating****
"""

from pykeen.pipeline import pipeline
from pykeen.models import DistMult, RotatE, TransE

# Dictionnaire des classes de modèles
model_classes = {
    'DistMult': DistMult,
    'RotatE': RotatE,
    'TransE': TransE,
}

selected_models = ['DistMult', 'RotatE', 'TransE']
trained_models_results = {}

for model_name in selected_models:
    print(f"\nEntraînement de {model_name}...")

    model_result = pipeline(
        model=model_classes[model_name],
        model_kwargs=dict(embedding_dim=50),
        training=training_triples,
        validation=validation_triples,
        testing=testing_triples,
        training_kwargs=dict(batch_size=64),
        stopper='early',
        stopper_kwargs=dict(
            frequency=10,
            patience=10,
            relative_delta=0.001,
            metric='mean_reciprocal_rank',
        ),
        random_seed=42,
        epochs=600
    )

    trained_models_results[model_name] = model_result
    print(f" {model_name} terminé.")

    evaluator = RankBasedEvaluator()

for model_name, result in trained_models_results.items():
    print(f"\nÉvaluation test pour {model_name}...")

    model = result.model
    additional_filter_triples = torch.cat([
        training_triples.mapped_triples,
        validation_triples.mapped_triples,
    ], dim=0)

    metrics = evaluator.evaluate(
        model=model,
        mapped_triples=testing_triples.mapped_triples
    )

    print(f"Raw metrics for {model_name} :")
    print(metrics.to_dict())

    result.metric_results = metrics

def evaluate_model(results, model_name):
    metrics = results.metric_results.to_dict()

    try:
        model_metrics = metrics['both']['realistic']
    except KeyError:
        model_metrics = metrics

    print(f"\nRésultats pour {model_name} :")
    metric_mapping = {
        'arithmetic_mean_rank': 'Mean Rank',
        'inverse_harmonic_mean_rank': 'Mean Reciprocal Rank',
        'hits_at_1': 'Hits At 1',
        'hits_at_3': 'Hits At 3',
        'hits_at_10': 'Hits At 10'
    }

    for metric_key, label in metric_mapping.items():
        value = model_metrics.get(metric_key)
        if value is not None:
            print(f"• {label} : {value:.4f}")
        else:
            print(f"• {label} : N/A")

for model_name, model_result in trained_models_results.items():
    print(f"\nAnalyse pour {model_name} :")

    entity_emb_module = model_result.model.entity_representations[0]
    relation_emb_module = model_result.model.relation_representations[0]

    model_entity_embs = entity_emb_module().detach().numpy()
    model_relation_embs = relation_emb_module().detach().numpy()

    print(f" • Entity embeddings shape : {model_entity_embs.shape}")
    print(f" • Relation embeddings shape : {model_relation_embs.shape}")

    evaluate_model(model_result, model_name)

"""**Visualization of Embeddings**"""

from plotly.subplots import make_subplots
import plotly.graph_objects as go

model_names = ['TransE', 'DistMult', 'RotatE']
methods = ['pca', 'tsne']
n_models = len(model_names)

fig = make_subplots(
    rows=2, cols=n_models,
    subplot_titles=[
        f"{model} – PCA" for model in model_names
    ] + [
        f"{model} – t-SNE" for model in model_names
    ],
    horizontal_spacing=0.05,
    vertical_spacing=0.15
)

color_pca = '#636EFA'
color_tsne = '#F4A7B9'

for row_idx, method in enumerate(methods, start=1):
    for col_idx, model_name in enumerate(model_names, start=1):
        model_result = trained_models_results[model_name]
        entity_embs = get_real_or_concatenated_embeddings(model_result.model.entity_representations[0])
        reduced = reduce_embeddings(entity_embs, method=method)
        entity_labels = [entity_id_to_label[i] for i in range(entity_embs.shape[0])]

        color = color_pca if method == 'pca' else color_tsne

        scatter = go.Scatter(
            x=reduced[:, 0],
            y=reduced[:, 1],
            mode='markers',
            text=entity_labels,
            hoverinfo='text',
            marker=dict(size=5, opacity=0.7, color=color),
            name=f"{model_name} – {method.upper()}",
            showlegend=False
        )

        fig.add_trace(scatter, row=row_idx, col=col_idx)

# Titre et mise en page
fig.update_layout(
    width=1050,
    height=700,
    title_text="Entity Embedding Projections ",
    margin=dict(t=60, b=30),
)

# Titres des axes
for i in range(1, n_models + 1):
    fig.update_xaxes(title_text="1st Component", row=1, col=i)
    fig.update_yaxes(title_text="2nd Component", row=1, col=i)
    fig.update_xaxes(title_text="t-SNE Dim 1", row=2, col=i)
    fig.update_yaxes(title_text="t-SNE Dim 2", row=2, col=i)

fig.show()

model_names = ['TransE', 'DistMult', 'RotatE']
methods = ['pca', 'tsne']
n_models = len(model_names)

fig = make_subplots(
    rows=2, cols=n_models,
    subplot_titles=[
        f"{model} – PCA (Relations)" for model in model_names
    ] + [
        f"{model} – t-SNE (Relations)" for model in model_names
    ],
    horizontal_spacing=0.05,
    vertical_spacing=0.15
)

color_pca = '#9ACD32'
color_tsne = '#F08080'

for row_idx, method in enumerate(methods, start=1):
    for col_idx, model_name in enumerate(model_names, start=1):
        model_result = trained_models_results[model_name]
        relation_embs = get_real_or_concatenated_embeddings(model_result.model.relation_representations[0])
        reduced = reduce_embeddings(relation_embs, method=method)
        relation_labels = [relation_id_to_label[i] for i in range(relation_embs.shape[0])]

        color = color_pca if method == 'pca' else color_tsne

        scatter = go.Scatter(
            x=reduced[:, 0],
            y=reduced[:, 1],
            mode='markers',
            text=relation_labels,
            hoverinfo='text',
            marker=dict(size=7, opacity=0.85, color=color, line=dict(width=0)),
            name=f"{model_name} – {method.upper()}",
            showlegend=False
        )

        fig.add_trace(scatter, row=row_idx, col=col_idx)

fig.update_layout(
    width=1050,
    height=700,
    title_text="Relation Embedding Projections",
    margin=dict(t=60, b=30),
)

for i in range(1, n_models + 1):
    fig.update_xaxes(title_text="1st Component", row=1, col=i)
    fig.update_yaxes(title_text="2nd Component", row=1, col=i)
    fig.update_xaxes(title_text="t-SNE Dim 1", row=2, col=i)
    fig.update_yaxes(title_text="t-SNE Dim 2", row=2, col=i)

fig.show()

def plot_similarity_dotplot(entities, similarity_dict, models):
    labels = [e.split('/')[-1] for e in entities]
    y = np.arange(len(labels))

    height = min(len(labels) * 0.4 + 2, 7)  # pour éviter un graphe immense
    fig, ax = plt.subplots(figsize=(10, height))

    colors = {
        'TransE': '#e78ac3',
        'DistMult': '#8da0cb',
        'RotatE': '#a6d854'
    }

    for i, model in enumerate(models):
        x = similarity_dict[model]
        ax.scatter(x, y, label=model, color=colors[model], s=60)

    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.set_xlabel("Cosine Similarity (Top-1 Neighbor)")
    ax.set_title("Top-1 Cosine Similarity per Entity (Nation-related concepts)")
    ax.invert_yaxis()
    ax.legend(loc='lower right')
    plt.grid(axis='x', linestyle='--', alpha=0.3)
    plt.tight_layout()
    plt.show()

plot_similarity_dotplot(entities, similarity_results, models)

"""This plot displays, for each entity related to the concept of nation, the cosine similarity between its embedding and that of its closest neighbor in the vector space. The three colored points per entity correspond to the scores obtained with TransE, DistMult, and RotatE respectively.By visualizing these top-1 similarity scores side by side, we can assess how each model organizes semantic proximity between entities.

TransE performs well on strongly connected entities such as Culture and United_Nations.
It captures simple relationships effectively but struggles with more abstract or ambiguous concepts.

DistMult consistently yields high and uniform similarity scores across entities.
It clusters similar entities efficiently but may overlook more nuanced relational structures.

RotatE shows more variation, with low similarity scores for several entities.
While it handles asymmetric and complex relations better, it appears less consistent on simpler cases.

**Link Prediction Examples**
"""

def predict_tail_entities(result, head_label, relation_label, k=5):
    model = result.model
    triples_factory = result.training

    entity_to_id = triples_factory.entity_to_id
    relation_to_id = triples_factory.relation_to_id
    id_to_entity = {v: k for k, v in entity_to_id.items()}

    if head_label not in entity_to_id or relation_label not in relation_to_id:
        raise ValueError("Head or relation label not found.")

    head_id = entity_to_id[head_label]
    relation_id = relation_to_id[relation_label]

    # Create tensor for (head, relation)
    head_relation_batch = torch.tensor([[head_id, relation_id]])

    # Score all possible tails
    scores = model.score_t(head_relation_batch)

    # Get top-k
    top_scores, top_indices = torch.topk(scores, k=k, dim=1)

    return [(id_to_entity[idx.item()], top_scores[0, i].item()) for i, idx in enumerate(top_indices[0])]

# Define the triple (head and relation)
head_label = 'http://dbpedia.org/resource/Nation'
relation_label = 'http://dbpedia.org/ontology/wikiPageWikiLink'
top_k = 5

# Run for each model
for model_name in ['TransE', 'DistMult', 'RotatE']:
    result = trained_models_results[model_name]
    print(f"\n Top {top_k} tail predictions for ({head_label.split('/')[-1]}, {relation_label.split('/')[-1]}, ?) using {model_name}:")

    try:
        predictions = predict_tail_entities(result, head_label, relation_label, k=top_k)
        for entity, score in predictions:
            print(f"  {entity} — score: {score:.4f}")
    except ValueError as e:
        print(f"  [Error in {model_name}]: {e}")

predictions_dict = {}
top_k = 5
head_label = 'http://dbpedia.org/resource/Nation'
relation_label = 'http://dbpedia.org/ontology/wikiPageWikiLink'

for model_name in ['TransE', 'DistMult', 'RotatE']:
    result = trained_models_results[model_name]
    try:
        preds = predict_tail_entities(result, head_label, relation_label, k=top_k)
        predictions_dict[model_name] = preds
    except ValueError as e:
        print(f"  [Error in {model_name}]: {e}")

import matplotlib.pyplot as plt

def plot_tail_predictions(predictions_dict):
    models = list(predictions_dict.keys())
    colors = {
        'TransE': '#e78ac3',
        'DistMult': '#8da0cb',
        'RotatE': '#a6d854'
    }

    fig, ax = plt.subplots(figsize=(10, 6))

    y_labels = []
    y_pos = []
    scores = []
    color_list = []

    offset = 0
    for model in models:
        preds = predictions_dict[model]
        for i, (entity_uri, score) in enumerate(preds):
            label = entity_uri.split('/')[-1]
            y_labels.append(label + f' ({model})')
            y_pos.append(offset + i)
            scores.append(score)
            color_list.append(colors[model])
        offset += len(preds) + 1  # espace entre groupes

    ax.barh(y_pos, scores, color=color_list)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(y_labels)
    ax.invert_yaxis()
    ax.set_xlabel("Score")
    ax.set_title("Top-5 Tail Predictions for (Nation, wikiPageWikiLink, ?)")
    plt.tight_layout()
    plt.show()
plot_tail_predictions(predictions_dict)